--- #YAML:1.0
name:               Astroboy
version:            1.05
abstract:           ~
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 1
    Cwd:                  3
    Exporter:             5
    File::Path:           1.08
    File::PathInfo:       1.25
    File::Which:          0.05
    Getopt::Std::Strict:  1.01
    LEOCHARRE::Class2:    1.13
    LEOCHARRE::CLI:       1.18
    LEOCHARRE::DEBUG:     1.11
    LEOCHARRE::Dir:       1.06
    MP3::Tag:             0.9713
    Smart::Comments:      1
    Test::Simple:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
